apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ingress-demo
spec:
  selector:
    app: api
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
  type: ClusterIP
